name: Stokomani Workflow

on:
  schedule:
    - cron: "0 3 1 * *" # Runs at 03:00 UTC on the first day of every month
  workflow_dispatch: # Allows manual triggering from the GitHub web interface

jobs:
  run-stokomani:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        working-directory: Stokomani
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run stokomani.py
        working-directory: Stokomani
        run: python stokomani.py

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install mr-cli
        working-directory: Stokomani
        run: npm install -g @maproulette/mr-cli

      - name: Run mr coop change
        working-directory: Stokomani
        run: mr coop change --out challenge.geojson stokomani.osm

      - name: Generate graphic
        working-directory: Stokomani
        run: python generate_graphic.py

      - name: Get the current date
        run: echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Update README with current date
        working-directory: Stokomani
        run: |
          sed -Ei "s/(Data last updated on:) [0-9\-]*/\1 '${{ env.current_date }}'/" README.md
          sed -Ei "s/(count_history\.png\?img_date=)[0-9\-]*/\1'${{ env.current_date }}'/" README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Stokomani ${{ env.current_date }}"
